sudo: false
language: node_js
node_js:
  - '0.12'
  - 'iojs-2'
  - 'iojs-1'
  - '4'
  - '6'
  - '7'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
